In [8]:
import numpy as np

### Unidimensional arrays

In [9]:
def printArray(array):
    print(array)
    print(f'Array shape: {array.shape}')

In [10]:
printArray(np.zeros(10))
printArray(np.ones(3))
printArray(np.full(8,1.5))
printArray(np.array([1,2,4,6,8,9]))
printArray(np.linspace(0,100,11))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array shape: (10,)
[1. 1. 1.]
Array shape: (3,)
[1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5]
Array shape: (8,)
[1 2 4 6 8 9]
Array shape: (6,)
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Array shape: (11,)


### MultiDimensional Arrays

In [11]:
printArray(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array shape: (4, 4)


In [12]:
array = np.array([
    [1,1,1],
    [2,2,2],
    [5,5,5],
    [9,9,9]
])

In [13]:
print(f'Just one element: {array[0,2]}')
print(f'Just one row: {array[2]}')
print(f'Just one column: {array[:,1]}')

Just one element: 1
Just one row: [5 5 5]
Just one column: [1 2 5 9]


### Randomly generated arrays 

In [14]:
np.random.seed(3)
np.random.rand(7,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ],
       [0.59086282, 0.02398188, 0.55885409],
       [0.25925245, 0.4151012 , 0.28352508]])

In [15]:
np.random.seed(3)
np.random.randn(3,3)

array([[ 1.78862847,  0.43650985,  0.09649747],
       [-1.8634927 , -0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068, -0.04381817]])

In [16]:
np.random.seed(3)
np.random.randint(0,20,(5,6))

array([[10,  3,  8,  0, 19, 10],
       [11,  9, 10,  6,  0, 12],
       [ 7, 14, 17,  2,  2,  1],
       [19,  5,  8, 14,  1, 10],
       [ 7, 11,  1, 15, 16,  5]])

### Operations and comparisons

In [17]:
# Random arrays
a = np.random.randint(0,20,(1,6))
b = np.random.randint(0,20,(1,6))

In [18]:
print(a,b)

[[17 14  0  0  9 18]] [[ 5  7  5 14  1 17]]


In [19]:
#Some operations
((b + a)/10)**2

array([[ 4.84,  4.41,  0.25,  1.96,  1.  , 12.25]])

In [20]:
#Comparison
b > a

array([[False, False,  True,  True, False, False]])

In [21]:
a[b > a]

array([0, 0])

In [22]:
a.min()

0

In [23]:
a.max()

18

In [24]:
b.std()

5.550275268448904

### Lineal Algebra

In [41]:
a = np.array([2,4,5,6])
b = np.array([1,0,0,2])

In [49]:
# element-wise multiplication
a * b

array([ 2,  0,  0, 12])

In [51]:
# dot product
np.dot(a,b)

14

In [57]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
#Compare matrices
np.equal(np.identity(5),np.eye(5))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [85]:
# Matrix inverse
a = np.random.randint(0,5,(3,3))
a

array([[3, 4, 1],
       [0, 1, 2],
       [3, 1, 0]])

In [86]:
# Inverse
aInv = np.linalg.inv(a)
aInv

array([[-0.13333333,  0.06666667,  0.46666667],
       [ 0.4       , -0.2       , -0.4       ],
       [-0.2       ,  0.6       ,  0.2       ]])

In [87]:
# matrix * Inverse = Identity
a.dot(aInv)

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 5.55111512e-17, -2.77555756e-17,  1.00000000e+00]])